services:
  redis:
    image: redis:latest
    container_name: redis-servidor
    #  garante que o contêiner reinicie automaticamente
    restart: always
    # O mapeamento de portas
    ports:
      - "6379:6379"
    # O mapeamento de volumes para persistência de dados.
    volumes:
      - dados-redis:/data
    command: redis-server --save 60 1 --loglevel warning

# ciclo de vida do volume.
volumes:
  dados-redis:
    driver: local