FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia o resto do código fonte
COPY . .

EXPOSE 5173

# O comando para iniciar o servidor de desenvolvimento
# Usar o script "dev" do package.json
CMD ["npm", "run", "dev"]